name: build_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Unit tests
        run: uv run poe test

      - name: Generate coverage lcov
        run: cd uw-alert-web && uv run coverage lcov

      - name: Report code coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: uw-alert-web
          path-to-lcov: uw-alert-web/coverage.lcov
          flag-name: run ${{ join(matrix.*, ' - ') }}
          parallel: true

  finish:
    needs: build_test
    if: ${{ always() }}
    runs-on: macos-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          carryforward: "run-3.10, run-3.11"
